name: Bug
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened
      description: "Describe the bug."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "What should have happened instead?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "How can someone trigger this bug?"
      placeholder: |
        1. Run `tofu apply`
        2. ...
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component
      description: "Which part of the stack is affected?"
      placeholder: "cert-manager / Traefik / Prometheus / Grafana / Loki / Forgejo / Woodpecker"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Logs, screenshots, or anything else that helps."
    validations:
      required: false
